/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * I 54KB API
 * NestJS 企业级后端服务 API，基于 Prisma + PostgreSQL + Redis + Socket.io，提供用户认证、审计日志、幂等性控制等核心能力
 * OpenAPI spec version: 1.0
 */

export type BindWechatDtoProvider =
  (typeof BindWechatDtoProvider)[keyof typeof BindWechatDtoProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BindWechatDtoProvider = {
  WECHAT_MINI: "WECHAT_MINI",
  WECHAT_MP: "WECHAT_MP",
  WECHAT_OPEN: "WECHAT_OPEN",
} as const;
