/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * I 54KB API
 * NestJS 企业级后端服务 API，基于 Prisma + PostgreSQL + Redis + Socket.io，提供用户认证、审计日志、幂等性控制等核心能力
 * OpenAPI spec version: 1.0
 */

export type ConfigItemControllerFindAllParams = {
  /**
   * 配置项 key（模糊查询）
   */
  key?: string;
  /**
   * 是否启用
   */
  isEnabled?: string | boolean;
  /**
   * 页码（从1开始）
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * 每页数量（默认1-100，此接口允许最大1000）
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
