/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * I 54KB API
 * NestJS 企业级后端服务 API，基于 Prisma + PostgreSQL + Redis + Socket.io，提供用户认证、审计日志、幂等性控制等核心能力
 * OpenAPI spec version: 1.0
 */

export type NamespaceControllerFindAllParams = {
  isEnabled?: string | boolean;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
  /**
   * 兼容参数：limit（迁移期保留；请使用 pageSize）
   * @deprecated
   */
  limit?: number;
};
