/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * I 54KB API
 * NestJS 企业级后端服务 API，基于 Prisma + PostgreSQL + Redis + Socket.io，提供用户认证、审计日志、幂等性控制等核心能力
 * OpenAPI spec version: 1.0
 */
import type { UpdateDictionaryDtoValue } from "./updateDictionaryDtoValue";
import type { UpdateDictionaryDtoDescription } from "./updateDictionaryDtoDescription";

export interface UpdateDictionaryDto {
  value?: UpdateDictionaryDtoValue;
  /**
   * @minLength 1
   * @maxLength 100
   */
  label?: string;
  description?: UpdateDictionaryDtoDescription;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  sort?: number;
  isEnabled?: boolean;
  /** @maxLength 20 */
  version?: string;
}
