/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * I 54KB API
 * NestJS 企业级后端服务 API，基于 Prisma + PostgreSQL + Redis + Socket.io，提供用户认证、审计日志、幂等性控制等核心能力
 * OpenAPI spec version: 1.0
 */
import type { UserControllerFindAllStatus } from "./userControllerFindAllStatus";

export type UserControllerFindAllParams = {
  /**
   * 用户 ID（Public ID，UUID，精确查询）
   */
  id?: string;
  /**
   * 邮箱（模糊查询）
   */
  email?: string;
  /**
   * 姓名（模糊查询）
   */
  name?: string;
  /**
   * 角色 ID（Public ID，UUID，精确查询）
   */
  roleId?: string;
  /**
   * 用户状态（ACTIVE|DISABLED|PENDING）
   */
  status?: UserControllerFindAllStatus;
  /**
   * 页码（从1开始）
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * 每页数量（1-100）
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
  /**
   * 兼容参数：limit（迁移期保留；请使用 pageSize）
   * @deprecated
   */
  limit?: number;
};
