/**
 * Error codes used in the unified API contract (ADR-API-001).
 *
 * - `code` is a stable string constant (grep-friendly, cross-end consistent)
 * - Success responses use `SUCCESS`
 * - Error responses should use a specific business code when possible; otherwise fall back to generic codes
 */

export const SUCCESS_CODE = "SUCCESS" as const;

export const ApiErrorCode = {
  // Generic
  SUCCESS: "SUCCESS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CSRF_FAILED: "CSRF_FAILED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  BAD_REQUEST: "BAD_REQUEST",

  // Idempotency
  IDEMPOTENCY_KEY_MISSING: "IDEMPOTENCY_KEY_MISSING",
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",
  IDEMPOTENCY_REQUIRES_AUTH: "IDEMPOTENCY_REQUIRES_AUTH",

  // Auth
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_USER_DISABLED: "AUTH_USER_DISABLED",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_REFRESH_TOKEN_EXPIRED: "AUTH_REFRESH_TOKEN_EXPIRED",
  AUTH_PHONE_CODE_EXPIRED: "AUTH_PHONE_CODE_EXPIRED",
  AUTH_PHONE_CODE_INVALID: "AUTH_PHONE_CODE_INVALID",
  AUTH_PHONE_RATE_LIMITED: "AUTH_PHONE_RATE_LIMITED",
  AUTH_WECHAT_CODE_INVALID: "AUTH_WECHAT_CODE_INVALID",
  AUTH_WECHAT_STATE_EXPIRED: "AUTH_WECHAT_STATE_EXPIRED",
  AUTH_IDENTITY_ALREADY_BOUND: "AUTH_IDENTITY_ALREADY_BOUND",
  AUTH_IDENTITY_NOT_FOUND: "AUTH_IDENTITY_NOT_FOUND",
  AUTH_IDENTITY_LAST_ONE: "AUTH_IDENTITY_LAST_ONE",

  // User/Role/Permission
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_DELETED: "USER_DELETED",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_SYSTEM_IMMUTABLE: "ROLE_SYSTEM_IMMUTABLE",
  ROLE_ALREADY_ASSIGNED: "ROLE_ALREADY_ASSIGNED",
  PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",
  PERMISSION_ALREADY_ASSIGNED: "PERMISSION_ALREADY_ASSIGNED",

  // Dictionary
  DICT_NOT_FOUND: "DICT_NOT_FOUND",
  DICT_KEY_EXISTS: "DICT_KEY_EXISTS",
  DICT_TYPE_INVALID: "DICT_TYPE_INVALID",

  // Config Center
  CONFIG_NAMESPACE_NOT_FOUND: "CONFIG_NAMESPACE_NOT_FOUND",
  CONFIG_NAMESPACE_EXISTS: "CONFIG_NAMESPACE_EXISTS",
  CONFIG_NAMESPACE_HAS_ITEMS: "CONFIG_NAMESPACE_HAS_ITEMS",

  CONFIG_ITEM_NOT_FOUND: "CONFIG_ITEM_NOT_FOUND",
  CONFIG_ITEM_EXISTS: "CONFIG_ITEM_EXISTS",
  CONFIG_SCHEMA_VALIDATION_FAILED: "CONFIG_SCHEMA_VALIDATION_FAILED",
  CONFIG_SCHEMA_INVALID: "CONFIG_SCHEMA_INVALID",
  CONFIG_ENCRYPTION_FAILED: "CONFIG_ENCRYPTION_FAILED",
  CONFIG_DECRYPTION_FAILED: "CONFIG_DECRYPTION_FAILED",

  CONFIG_VERSION_NOT_FOUND: "CONFIG_VERSION_NOT_FOUND",
  CONFIG_ROLLBACK_FAILED: "CONFIG_ROLLBACK_FAILED",

  // Script Upload
  SCRIPT_FEATURE_DISABLED: "SCRIPT_FEATURE_DISABLED",
  SCRIPT_TOKEN_MISSING: "SCRIPT_TOKEN_MISSING",
  SCRIPT_TOKEN_INVALID: "SCRIPT_TOKEN_INVALID",
  SCRIPT_DATA_NOT_FOUND: "SCRIPT_DATA_NOT_FOUND",

  // Navigation
  NAV_GROUP_NOT_FOUND: "NAV_GROUP_NOT_FOUND",
  NAV_GROUP_CODE_EXISTS: "NAV_GROUP_CODE_EXISTS",
  NAV_GROUP_NOT_OWNER: "NAV_GROUP_NOT_OWNER",
  NAV_GROUP_HAS_ITEMS: "NAV_GROUP_HAS_ITEMS",
  NAV_ITEM_NOT_FOUND: "NAV_ITEM_NOT_FOUND",
  NAV_ITEM_NOT_OWNER: "NAV_ITEM_NOT_OWNER",
  NAV_ITEM_INVALID_GROUP: "NAV_ITEM_INVALID_GROUP",

  // XiaoHongShu (example module)
  XHS_ACCOUNT_NOT_FOUND: "XHS_ACCOUNT_NOT_FOUND",
  XHS_AUTH_EXPIRED: "XHS_AUTH_EXPIRED",
  XHS_AUTH_INVALID: "XHS_AUTH_INVALID",
  XHS_API_ERROR: "XHS_API_ERROR",
  XHS_REQUEST_FAILED: "XHS_REQUEST_FAILED",
  XHS_RATE_LIMITED: "XHS_RATE_LIMITED",
  XHS_SYNC_IN_PROGRESS: "XHS_SYNC_IN_PROGRESS",
  XHS_SYNC_FAILED: "XHS_SYNC_FAILED",

  // System/Dependencies
  DATABASE_ERROR: "DATABASE_ERROR",
  REDIS_ERROR: "REDIS_ERROR",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  DB_FOREIGN_KEY_VIOLATION: "DB_FOREIGN_KEY_VIOLATION",
  DB_INVALID_VALUE: "DB_INVALID_VALUE",
  DB_VALUE_OUT_OF_RANGE: "DB_VALUE_OUT_OF_RANGE",
  DB_RELATION_VIOLATION: "DB_RELATION_VIOLATION",
  DB_INPUT_ERROR: "DB_INPUT_ERROR",
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
